use_frameworks!

platform :ios, '8.0'

target 'LWaabbccd_Example' do
  pod 'LWaabbccd', :path => '../'

  target 'LWaabbccd_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
